#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
wal -i /home/adrian/Downloads/wolf.jpeg

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          10
bspc config pointer_follows_focus false
bspc config focus_follows_pointer true
#### BSPWM configuration ####
bspc config top_padding          0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

$HOME/.config/polybar/launch.sh
$HOME/adrian/.phicom
wal -R
dunst &
